AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  scheduled-event-adjuster

  This solution adjusts the schedules of scheduled Auto Scaling Group scaling
  actions to account for hour changes due to Daylight Saving Time.

Parameters:
  NotificationEmail:
    Type: String
    Description: The email address that should be notified when relevant events
      occur.
  TagPrefix:
    Type: String
    Description: (Optional) The tag prefix to use when checking resources'
      tags. Leave empty to use the default prefix.
    Default: 'scheduled-event-adjuster'
  WinterTriggerMonth:
    Type: Number
    Description: The month when the winter DST change will be triggered. 1=January, 12=December
    MinValue: 1
    MaxValue: 12
  WinterTriggerDay:
    Type: Number
    Description: The day when the winter DST change will be triggered. 1 to 31
    MinValue: 1
    MaxValue: 31
  WinterTriggerHour:
    Type: Number
    Description: The hour when the winter DST change will be triggered. 0 to 23
    MinValue: 0
    MaxValue: 23
  WinterTriggerMinute:
    Type: Number
    Description: The minute when the winter DST change will be triggered. 0 to 59
    MinValue: 0
    MaxValue: 59
  SummerTriggerMonth:
    Type: Number
    Description: The month when the summer DST change will be triggered. 1=January, 12=December
    MinValue: 1
    MaxValue: 12
  SummerTriggerDay:
    Type: Number
    Description: The day when the summer DST change will be triggered. 1 to 31
    MinValue: 1
    MaxValue: 31
  SummerTriggerHour:
    Type: Number
    Description: The hour when the summer DST change will be triggered. 0 to 23
    MinValue: 0
    MaxValue: 23
  SummerTriggerMinute:
    Type: Number
    Description: The minute when the summer DST change will be triggered. 0 to 59
    MinValue: 0
    MaxValue: 59

Globals:
  Function:
    Timeout: 10

Resources:
  AdjustScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: adjust_schedule_function
      Handler: adjust_schedule/app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          TAG_PREFIX: !Ref TagPrefix
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: 'AllowProcessingAutoScalingGroups'
              Effect: 'Allow'
              Action:
                - 'autoscaling:DescribeAutoScalingGroups'
                - 'autoscaling:DescribeScheduledActions'
                - 'autoscaling:BatchPutScheduledUpdateGroupAction'
              Resource: '*'
            - Sid: 'AllowProcessingEventBridgeRules'
              Effect: 'Allow'
              Action:
                - 'events:ListRules'
                - 'events:ListTagsForResource'
                - 'events:PutRule'
              Resource: '*'
        - EventBridgePutEventsPolicy:
            EventBusName: default

  WinterTrigger:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - scheduled-event-adjuster
        detail-type:
          - 'ManualTrigger'
      ScheduleExpression: !Join
        - ''
        - - 'cron('
          - !Ref WinterTriggerMinute
          - ' '
          - !Ref WinterTriggerHour
          - ' ' 
          - !Ref WinterTriggerDay
          - ' '
          - !Ref WinterTriggerMonth
          - ' ? *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt AdjustScheduleFunction.Arn
          Id: adjust-schedule-lambda-function

  WinterTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AdjustScheduleFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt WinterTrigger.Arn

  SummerTrigger:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - scheduled-event-adjuster
        detail-type:
          - 'ManualTrigger'
      ScheduleExpression: !Join
        - ''
        - - 'cron('
          - !Ref SummerTriggerMinute
          - ' '
          - !Ref SummerTriggerHour
          - ' ' 
          - !Ref SummerTriggerDay
          - ' '
          - !Ref SummerTriggerMonth
          - ' ? *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt AdjustScheduleFunction.Arn
          Id: adjust-schedule-lambda-function

  SummerTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AdjustScheduleFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SummerTrigger.Arn
  #
  # EventBridge subscription to notify about a completion via SNS
  #
  CompletionNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email

  CompletionNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: 'CompletionNotificationTopicPolicy'
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowPublishingFromEventBridge'
            Effect: 'Allow'
            Principal:
              Service: 'events.amazonaws.com'
            Action: 'sns:Publish'
            Resource: !Ref CompletionNotificationTopic
      Topics:
        - !Ref CompletionNotificationTopic

  NotifyOnCompletion:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - scheduled-event-adjuster
        detail-type:
          - 'ProcessCompleted'
      State: ENABLED
      Targets:
        - Arn: !Ref CompletionNotificationTopic
          Id: completion-notification-sns-topic
  #
  # End of subscription
  #
